name: Build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    name: Build (${{ matrix.name }})

    strategy:
      matrix:
        include:
          - name: win-32
            target: i686-pc-windows-msvc
            artifact_name: takure_32
          - name: win-64
            target: x86_64-pc-windows-msvc
            artifact_name: takure_64

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

    - name: Cache
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 #v2.9.2
      with:
          key: ${{ matrix.target }}

    - name: Add build target
      run: rustup target add ${{ matrix.target }}

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Copy .toml file
      run: cp takure.toml target/${{ matrix.target }}/release/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          target/${{ matrix.target }}/release/takure.dll
          target/${{ matrix.target }}/release/takure.toml
